{application,chat,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{chat_app,[]}},
              {env,[]},
              {modules,[chat_app,chat_client,chat_client_new,chat_server,
                        chat_sup]}]}.
